version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "avacom"
resolve_s3 = true
s3_prefix = "avacom"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
